name: VPN Config Update Notification

on:
  push:
    paths:
      - 'configs/**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        run: |
          MESSAGE="🔔 Доступно новое обновление.%0A%0AПожалуйста, обновите конфиг в вашем VPN-клиенте."

          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="@internetbetterfree" \
            -d text="$MESSAGE"
