name: VPN Config Update Notification

on:
  push:
    branches:
      - main  # Замени на master, если у тебя основная ветка называется master
    paths:
      - 'configibf'
      - 'configibf2'
      # Если файлы лежат в папке, укажи путь: 'configs/configibf'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="@internetbetterfree" \
            -d text="🔔 Обновлён VPN конфиг. Обновите клиент."
